export type CardLogProps = {
  user: string;
  userId: string;
  Amount: string;
  CardApprovalCost: string;
  CardApprovalNum: string;
  CardApprovalType: string;
  CardNum: string;
  CorpName: string;
  cardCompany: string;
  CorpNum: string;
  Currency: string;
  InstallmentMonths: string;
  PaymentPlan: string;
  ServiceCharge: string;
  Tax: string;
  TotalAmount: string;
  UseDT: string;
  UseStoreAddr: string;
  UseStoreBizType: string;
  UseStoreCorpNum: string;
  UseStoreName: string;
  UseStoreNum: string;
  UseStoreTaxType: string;
  UseStoreTel: string;
  transDate: Date;
  keyword: Array<string>;
};
