export type FinItemProps = {
  _id: string;
  user: string;
  userId: string;
  account: string;
  card: string;
  itemKind: string;
  itemKindName: string;
  itemType: string;
  itemTypeName: string;
  finCorpCode: string;
  finCorpName: string;
  itemName: string;
  accountNum: string;
  defaultDate: Date;
  currentAmount: number;
  isFixed: boolean;
  createdAt?: Date;
  corpNum: string;
  corpName: string;
  finItemName: string;
  finItemCode: string;
  finName: string;
  transRemark: string;
  useYn: boolean;
  amount: number;
};
